[package]
name = "zakura_mmr_tree"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "Zcash chain history Merkle mountain range tree for Zakura"
readme = "README.md"
keywords.workspace = true
categories = ["cryptography::cryptocurrencies", "data-structures"]

[dependencies]
blake2b_simd.workspace = true
byteorder.workspace = true
uint.workspace = true

[dev-dependencies]
proptest.workspace = true

[lib]
bench = false

[lints]
workspace = true
