services:
  zebra:
    container_name: zebra
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: tests
    volumes:
      - zakurad-cache:/home/zebra/.cache/zakura
      - lwd-cache:/home/zebra/.cache/lwd
    env_file:
      - test.env

volumes:
  zakurad-cache:
    driver: local

  lwd-cache:
    driver: local
