d /var/log/zakura 0755 root root -
d /var/log/zakura/runs 0755 root root -
d /var/lib/zakura-continuous-sync 0755 root root -
d /var/lib/zakura-continuous-sync/build-cache 0755 root root -
d /var/lib/zakura-monitor 0755 root root -
