[package]
name = "zakura-orchard-merkle-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
zakura-chain = { path = "../../crates/zakura-chain", features = ["fuzz-impl"] }

[[bin]]
name = "orchard_merkle_equivalence"
path = "fuzz_targets/orchard_merkle_equivalence.rs"
test = false
doc = false
bench = false

[workspace]
