[network]
network = "Mainnet"
p2p_stack = "legacy"
listen_addr = "127.0.0.1:28234"
cache_dir = "/Library/Application Support/ZakuraVerifier/peers"

[state]
cache_dir = "/Library/Application Support/ZakuraVerifier"
storage_mode = "pruned"

[consensus]
checkpoint_sync = false
vct_fast_sync = false

[sync]
download_concurrency_limit = 4
full_verify_concurrency_limit = 2
parallel_cpu_threads = 4

[rpc]
listen_addr = "127.0.0.1:28232"
enable_cookie_auth = false
