//! Test-only indexer mTLS certificates.

pub(super) const CA_CERT: &str = r#"-----BEGIN CERTIFICATE-----
MIIBhjCCAS2gAwIBAgIUVo+S2OeXFdj9ryT71Hnx2JeQLfYwCgYIKoZIzj0EAwIw
GTEXMBUGA1UEAwwOWmFrdXJhLVRlc3QtQ0EwHhcNMjYwODA1MTI1NjAxWhcNMzYw
ODAyMTI1NjAxWjAZMRcwFQYDVQQDDA5aYWt1cmEtVGVzdC1DQTBZMBMGByqGSM49
AgEGCCqGSM49AwEHA0IABCzXZGhiCIkL9vI/dCDoNAsowfIW2VyJXjtJ8TiuORf9
wKb8IU2k0kRCefm7msLkqzFSyskCNgx+imBRgLjpHqajUzBRMB0GA1UdDgQWBBSX
+PYNZtEk7ozgq+vTlL7VaD/l8TAfBgNVHSMEGDAWgBSX+PYNZtEk7ozgq+vTlL7V
aD/l8TAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cAMEQCIHpspYo34BVt
FpVYm+dHPIiO47p0oW1sIYxHndmZpNfaAiB1mp1GsbDE669od7mxPvjR2p1d/al9
brqJAhNx08jeLA==
-----END CERTIFICATE-----
"#;

pub(super) const SERVER_CERT: &str = r#"-----BEGIN CERTIFICATE-----
MIIBejCCASCgAwIBAgIBATAKBggqhkjOPQQDAjAZMRcwFQYDVQQDDA5aYWt1cmEt
VGVzdC1DQTAeFw0yNjA4MDUxMjU2MjFaFw0zNjA4MDIxMjU2MjFaMBQxEjAQBgNV
BAMMCWxvY2FsaG9zdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJ5e+/edfTsD
x59OQxfKjzkw0TtrEFJdP/d7E4YbNwCJoKlEmy/YB6cIFa2+kLjNGmycD1lEXTdC
3TPoyiXefPOjXjBcMBoGA1UdEQQTMBGCCWxvY2FsaG9zdIcEfwAAATAdBgNVHQ4E
FgQU6i4kvcyWjmFUahnOT2wLGQf1MYswHwYDVR0jBBgwFoAUl/j2DWbRJO6M4Kvr
05S+1Wg/5fEwCgYIKoZIzj0EAwIDSAAwRQIhAJIlhHuUhZVjdULb5ZqmsLKKeXdu
gk/OzGWexXkwHwgxAiA6CCR6OufAXl6cTQruvj3U5Hnqwq1Or9fzmbj4wbiQ8A==
-----END CERTIFICATE-----
"#;

/// An expired server certificate with the same public key as [`SERVER_KEY`], valid from
/// 2025-01-01 00:00:00 UTC to 2025-02-01 00:00:00 UTC.
pub(super) const EXPIRED_SERVER_CERT: &str = r#"-----BEGIN CERTIFICATE-----
MIIBNzCB3qADAgECAgECMAoGCCqGSM49BAMCMBQxEjAQBgNVBAMMCWxvY2FsaG9z
dDAeFw0yNTAxMDEwMDAwMDBaFw0yNTAyMDEwMDAwMDBaMBQxEjAQBgNVBAMMCWxv
Y2FsaG9zdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJ5e+/edfTsDx59OQxfK
jzkw0TtrEFJdP/d7E4YbNwCJoKlEmy/YB6cIFa2+kLjNGmycD1lEXTdC3TPoyiXe
fPOjITAfMB0GA1UdDgQWBBTqLiS9zJaOYVRqGc5PbAsZB/UxizAKBggqhkjOPQQD
AgNIADBFAiB7ZQ6KWjbYkSXyAhHdJ8PphIh+M4GYexDKKzq82CtEygIhAOAU7hPL
sm9IFiqlM+wRullgmq4xC97VmzpxNRJLhagc
-----END CERTIFICATE-----
"#;

/// A not-yet-valid server certificate with the same public key as [`SERVER_KEY`], valid from
/// 2099-01-01 00:00:00 UTC to 2100-01-01 00:00:00 UTC.
pub(super) const NOT_YET_VALID_SERVER_CERT: &str = r#"-----BEGIN CERTIFICATE-----
MIIBOzCB4qADAgECAgEDMAoGCCqGSM49BAMCMBQxEjAQBgNVBAMMCWxvY2FsaG9z
dDAiGA8yMDk5MDEwMTAwMDAwMFoYDzIxMDAwMTAxMDAwMDAwWjAUMRIwEAYDVQQD
DAlsb2NhbGhvc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASeXvv3nX07A8ef
TkMXyo85MNE7axBSXT/3exOGGzcAiaCpRJsv2AenCBWtvpC4zRpsnA9ZRF03Qt0z
6Mol3nzzoyEwHzAdBgNVHQ4EFgQU6i4kvcyWjmFUahnOT2wLGQf1MYswCgYIKoZI
zj0EAwIDSAAwRQIhAIk5EsjxM2q6RUWSPLXS1g7ocPJsPkmSjKYPZDD9JginAiAN
VHKxGoekM8PjN/JMeSFcBbM36w+6t7H1bsqHZb1iGw==
-----END CERTIFICATE-----
"#;

pub(super) const SERVER_KEY: &str = r#"-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIHSxPJZ4QdLJAZA79S2D8CDKrV5AnfRv0JCk+Qr0IXGLoAoGCCqGSM49
AwEHoUQDQgAEnl779519OwPHn05DF8qPOTDRO2sQUl0/93sThhs3AImgqUSbL9gH
pwgVrb6QuM0abJwPWURdN0LdM+jKJd588w==
-----END EC PRIVATE KEY-----
"#;

pub(super) const CLIENT_CERT: &str = r#"-----BEGIN CERTIFICATE-----
MIIBZzCCAQ2gAwIBAgIBAjAKBggqhkjOPQQDAjAZMRcwFQYDVQQDDA5aYWt1cmEt
VGVzdC1DQTAeFw0yNjA4MDUxMjU2MjFaFw0zNjA4MDIxMjU2MjFaMB0xGzAZBgNV
BAMMElpha3VyYS1UZXN0LUNsaWVudDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
BNCIlLA6c9MyCNcsNLmI3+JviyaS08w3UHGf7WbArTfXVI3PXCcZLxU3z29E/hkf
fM3/pGzmcO112pAFSIguLw2jQjBAMB0GA1UdDgQWBBTqjYof3xaZAyXf7ge+75HF
Zc9TRTAfBgNVHSMEGDAWgBSX+PYNZtEk7ozgq+vTlL7VaD/l8TAKBggqhkjOPQQD
AgNIADBFAiEA7cdNBqMC28YnQOaSogAPSY24YblvBNRBQCmbrWiYEE0CIChQdOdF
n2NsDl18gaHlQpKPQxYleVGiI6NDjTNsnLO3
-----END CERTIFICATE-----
"#;

pub(super) const CLIENT_KEY: &str = r#"-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIC5IErifZauipv/mTmTTmoxpzhsMVAPI5AiePyOUrRPMoAoGCCqGSM49
AwEHoUQDQgAE0IiUsDpz0zII1yw0uYjf4m+LJpLTzDdQcZ/tZsCtN9dUjc9cJxkv
FTfPb0T+GR98zf+kbOZw7XXakAVIiC4vDQ==
-----END EC PRIVATE KEY-----
"#;

/// A client certificate signed by a second CA that the server does not trust,
/// `CN=Zakura-Test-Untrusted-CA`. Otherwise identical in shape to
/// [`CLIENT_CERT`]: P-256, ecdsa-with-SHA256, serial 2, same validity window.
pub(super) const UNTRUSTED_CLIENT_CERT: &str = r#"-----BEGIN CERTIFICATE-----
MIIBejCCASGgAwIBAgIBAjAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhaYWt1cmEt
VGVzdC1VbnRydXN0ZWQtQ0EwHhcNMjYwODA1MTI1NjIxWhcNMzYwODAyMTI1NjIx
WjAnMSUwIwYDVQQDDBxaYWt1cmEtVGVzdC1VbnRydXN0ZWQtQ2xpZW50MFkwEwYH
KoZIzj0CAQYIKoZIzj0DAQcDQgAEZryAGuC1THWnd59RQiTwDSLzqSknT8nvOFgb
itGEkTugY8wbpPDhtGqHEFlHLyc9pqLToF1dZcuydKKfhOZL+qNCMEAwHQYDVR0O
BBYEFKXHrQvSGa9GvmdX2vSh1c1gYOrmMB8GA1UdIwQYMBaAFB0upmQpvEkhxChh
e4j0YJJokeaPMAoGCCqGSM49BAMCA0cAMEQCIEe+Aop1mVwghhxIfuvMpotexJSL
cn9ij3bghmh081AYAiBeOK3Sj3z4V7yipqDlSRUeH41rns8Mz7mVUD0UWYzgSQ==
-----END CERTIFICATE-----
"#;

pub(super) const UNTRUSTED_CLIENT_KEY: &str = r#"-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIOfYiR9PgYMG8//jYaabLGknn1T+djREn5CzGoB0gIq6oAoGCCqGSM49
AwEHoUQDQgAEZryAGuC1THWnd59RQiTwDSLzqSknT8nvOFgbitGEkTugY8wbpPDh
tGqHEFlHLyc9pqLToF1dZcuydKKfhOZL+g==
-----END EC PRIVATE KEY-----
"#;
