/srv/zakura-profile/data/collector.log /srv/zakura-profile/data/sampler.log /srv/zakura-profile/data/raw/*/record.stderr {
    size 8M
    rotate 2
    compress
    copytruncate
    missingok
    notifempty
    su root zakura-profile
}
