[book]
authors = ["Zakura contributors"]
language = "en"
src = "src"
title = "The Zakura Book"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["theme/css/custom.css"]
